LSB Core requires init scripts to return specific exit codes

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -36,3 +36,25 @@ script:
     | grep -q "ACCEPT.*dpt:9123"
     && (echo 'Port 9123 is open - pass' && exit 0)
     || (echo 'Port 9123 is not open - fail' && exit 1)
+
+  # Check running firewall has exit code 0
+  - >
+    sudo service firewall status
+    && (echo 'Status of running firewall is 0 - pass' && exit 0)
+    || (echo 'Status of running firewall is not 0 - fail' && exit 1)
+
+  # Stop firewall
+  - >
+    sudo service firewall stop
+    && (echo 'Stopping firewall - pass' && exit 0)
+    || (echo 'Stopping firewall - fail' && exit 1)
+
+  # Check stopped firewall has exit code 3
+  - >
+    sudo service firewall status;
+    EXIT=$?;
+    if [ 3 -eq $EXIT ]; then
+      echo 'Status of stopped firewall is 3 - pass' && exit 0;
+    else
+      echo 'Status of stopped firewall is not 3 - fail' && exit 1;
+    fi 
